name: heaven
version: 1.0.0-dev+3
description: Isomorphic library to create nested templates. Supports string rendering, DOM rendering and virtual DOM.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/heaven
dependencies:
  angel_framework: ">=1.0.0-dev <2.0.0"
dev_dependencies:
  browser: ">=0.10.0 < 0.11.0"
  test: ">=0.12.13 <0.13.0"
