name: heaven
version: 0.0.0-dev+1
description: A minimal virtual DOM implementation.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/heaven
dev_dependencies:
  test: "^0.12.13+5"