name: heaven
description: A client-side rendering library ideal for reactive SPA's.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/heaven
dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.1
  test: "^0.12.13+5"
transformers:
- dart_to_js_script_rewriter