name: heaven
description: A client-side rendering library ideal for reactive SPA's.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/heaven
dependencies:
  browser: "^0.10.0+2"
